apiVersion: 1

datasources:
  - name: AgroSmart TimescaleDB
    uid: agrosmart_timescale
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: ${AGROSMART_DB_NAME}
    user: ${AGROSMART_DB_USER}
    secureJsonData:
      password: ${AGROSMART_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: false
